'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HotDocs_HP_WordAddIn.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;root xmlns=&quot;http://www.homoki.net/uri/customXMLcontracts/&quot; 
        '''xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        '''xsi:schemaLocation=&quot;http://www.homoki.net/uri/customXMLcontracts/ customXMLContracts.xsd&quot;&gt;
        '''&lt;HotDocsReferences&gt;
        '''&lt;ClientName/&gt;
        '''&lt;ClientAddress/&gt;
        '''&lt;ClientObligatoryMiscInformation/&gt;
        '''&lt;ClientRegisterFullData/&gt;
        '''&lt;ClientRegisterName/&gt;
        '''&lt;ClientRegistrationIdentifier/&gt;
        '''&lt;ClientSignatureDate/&gt;
        '''&lt;ClientSignaturePlace/&gt;
        '''&lt;ClientTaxNumberHun/&gt;
        '''&lt;ClientTaxNumber/&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property blank_customXMLContracts() As String
            Get
                Return ResourceManager.GetString("blank_customXMLContracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; targetNamespace=&quot;http://www.homoki.net/uri/customXMLcontracts/&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        '''  &lt;xs:element name=&quot;root&quot;&gt;
        '''    &lt;xs:annotation&gt;
        '''      &lt;xs:documentation&gt;szerződés típusa/tárgya = dc:subject, dc:keywords, dc:description, dc:contentstatus, szerződés címe = dc:title, dc:date = Date of last signature or usual date used for dating, szerző = Author (Word) = dc:creator&lt;/xs:documentation&gt;
        '''    &lt;/xs:annotation&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property customXMLContracts() As String
            Get
                Return ResourceManager.GetString("customXMLContracts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to díjt;díjat
        '''vételárt;vételárat
        '''árt;árat
        '''Díjt;Díjat
        '''Vételárt;Vételárat
        '''Árt;Árat
        '''óradíjt;óradíjat
        '''napidíjt;napidíjat
        '''hetidíjt;hetidíjat
        '''havidíjt;havidíjat
        '''Megbízott-tól;Megbízottól
        '''Megbízott-tat;Megbízottat
        '''Megbízott-tal;Megbízottal
        '''Igénybevesző;Igénybevevő
        '''Igénybeveszőt;Igénybevevőt
        '''Igénybeveszőnek;Igénybevevőnek
        '''Igénybeveszőtől;Igénybevevőtől
        '''Igénybeveszőnél;Igénybevevőnél
        '''Igénybeveszőhöz;Igénybevevőhöz
        '''Igénybeveszőről;Igénybevevőről
        '''Igénybeveszővé;Igénybevevővé
        '''Igénybeveszővel;Igénybeve [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DeclinationConjugationExceptions() As String
            Get
                Return ResourceManager.GetString("DeclinationConjugationExceptions", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
